language: node_js

node_js: 10

script:
 - yarn clean
 - yarn build

cache:
  directories:
    - node_modules

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: public
  on:
    branch: master

branches:
  only:
  - master

git:
  depth: 3
